### ISSUE TITLE
Finalize and implement soft and hard delete function for all services

### ISSUE THREAD

**Issue by Jess-White** [Jess-White/boilerplate#165]
The delete function is not consistent throughout the app, because it was sorta-implemented at different times. 
- Boilerplates
- Categories
- Funding Orgs
- Grants
- Sections
- Reports
- Report Sections

For all tables we need: 
- a "soft delete" function that sends a patch request to the backend to toggle the "archived" column from "false" to "true" 
- an "undelete" function for archive-index objects that that sends a patch request to the backend to toggle the "archived" column from "true to "false" 

- as reflected on the Figma (...we might need to make more decisions about this :)) filtering functions to shunt archived:true objects to an archived tab or filter view
- for some of these - sections, report sections - we would probably not need an "archived" view
- for some of these - sections, report sections, maybe all? - a "restore" option immediately post delete

- a "hard delete" function that deletes everything where archived:true and last_updated_at: more than three years ago
(maybe separate ticket?) 
- need dependent destroy for grants/sections, reports/report_sections 
- definitely NOT dependent destroy for everything else!
- should we even have hard delete for organizations? funding orgs? or is it even necessary to remove them from the database?

**Comment by cainwatson** [comment]
https://github.com/rubysherpas/paranoia
